export { default as laptopImg } from "./laptop.png";
export { default as meImg } from "./me.jpg";
export { default as quizImg } from "./quiz.png";
export { default as pomImg } from "./pom_final.png";
export { default as promptopiaImg } from "./promptopia_final.png";
export { default as galleryImg } from "./photo_final.png";
export { default as pizzaImg } from "./pizza_final.png";
export { default as messangerImg } from "./messanger_final.png";
export { default as meLogoImg } from "./me_logo.png";
